import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
assert.match(html,/lang="zh-CN"/);
assert.match(html,/妆疯了：整活工作室 V3\.5/);
assert.match(html,/id="beauty-actor-canvas"/);
assert.match(html,/原创参数化三维美漫角色/);
assert.match(html,/37件可视化化妆品/);
assert.match(html,/42份手工合同/);
assert.match(html,/16种行为模块/);
assert.match(html,/6种自然流派/);
assert.match(html,/Array\.from\(\{length:42\}/);
assert.equal((html.match(/product\('/g)||[]).length,37,'必须正好声明37件首发可视产品');
for(const name of ['柔焦粉底液','蜜桃腮红','大地色眼影盘','黑曜眼线笔','浓密睫毛膏','玫瑰雾面口红','镜面唇蜜','全息亮片胶','长效定妆喷雾']) assert.ok(html.includes(name),`缺少产品 ${name}`);
for(const m of ['镜像核心','余色记忆','复写回路','二次涂层','虹吸阀','连锁反应器','膨胀模块','收缩模块','回弹模块','风返模块','自动追踪芯片','延迟爆发器','路径分叉器','冻结定型','事故转热度','紫外共鸣']) assert.ok(html.includes(m),`缺少行为模块 ${m}`);
for(const b of ['精准磁轨流','色彩炼金流','五官雕塑流','气象控制流','事故电视流','复制自动化流']) assert.ok(html.includes(b),`缺少Build ${b}`);
assert.equal(/https?:\/\//.test(html),false,'发布HTML不得包含运行时远程地址');
assert.equal(/<script[^>]+src=/.test(html),false,'发布HTML不得依赖外部脚本');
assert.equal(/<link[^>]+href=/.test(html),false,'发布HTML不得依赖外部样式');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
assert.equal(scripts.length,1,'应有且仅有一个内联运行脚本');
new Function(scripts[0][1]);
console.log('STATIC_GATE_PASS',JSON.stringify({products:37,contracts:42,mutators:16,builds:6,offline:true,inline:true}));
